import aviatorImage from "@assets/aviator.jpg";
import blackjackLiveImage from "@assets/placeHolders/blackjackLive.jpg";
import bonanzaImage from "@assets/placeHolders/bonanza.jpg";
import bookOfHeadImage from "@assets/placeHolders/bookOfHead.jpg";
import fireStrikeImage from "@assets/placeHolders/fireStrike.jpg";
import rouletteImage from "@assets/placeHolders/roulette.jpg";
import type {
    CasinoGameRailCardData,
    CasinoGameRailIconId,
    CasinoGameRailVariant,
} from "./types";

export const casinoGameRailSeeAllLabel = "Ver";

export const casinoGameRailSeeAllLabels: Record<CasinoGameRailVariant, string> = {
    rank: "Ver",
    time: "Ver",
    popular: "Ver",
    topGames: "Ver",
    launches: "Ver",
    jackpots: "Ver",
    megaways: "Ver",
    forYou: "Ver",
    basedOn: "Ver",
    similar: "Ver",
    trending: "Ver",
    upcoming: "Ver",
    liveTop: "Ver",
    liveRoulette: "Ver",
    liveBlackjack: "Ver",
    liveBaccarat: "Ver",
    liveGameShows: "Ver",
    livePoker: "Ver",
    favRecent: "Ver",
    favPlayed: "Ver",
    favSlots: "Ver",
    favLive: "Ver",
    favDiscover: "Ver",
    tourSoon: "Ver",
    tourMine: "Ver",
    tourDone: "Ver historial",
};

export const casinoGameRailTitles: Record<CasinoGameRailVariant, string> = {
    rank: "Top 10",
    time: "Últimos jugados",
    popular: "Popular Ahora",
    topGames: "Top Juegos",
    launches: "Nuevos Lanzamientos",
    jackpots: "Mega Jackpots",
    megaways: "Slots Megaways",
    forYou: "Top Picks Para Ti",
    basedOn: "Basado en tus juegos",
    similar: "Jugadores similares eligen",
    trending: "Tendencias de esta semana",
    upcoming: "Próximos grandes premios",
    liveTop: "Top 10",
    liveRoulette: "Ruletas en Vivo",
    liveBlackjack: "Blackjack en Vivo",
    liveBaccarat: "Baccarat en Vivo",
    liveGameShows: "Game Shows",
    livePoker: "Poker en Vivo",
    favRecent: "Recién agregados",
    favPlayed: "Más jugados",
    favSlots: "Slots favoritos",
    favLive: "Casino en vivo favorito",
    favDiscover: "Por Descubrir",
    tourSoon: "Próximamente",
    tourMine: "Mis Torneos",
    tourDone: "Finalizados",
};

export const casinoGameRailIcons: Record<CasinoGameRailVariant, CasinoGameRailIconId> = {
    rank: "trophy",
    time: "clock",
    popular: "flame",
    topGames: "flame",
    launches: "sparkles",
    jackpots: "coins",
    megaways: "gem",
    forYou: "star",
    basedOn: "gamepad",
    similar: "users",
    trending: "trending",
    upcoming: "gem",
    liveTop: "trophy",
    liveRoulette: "dices",
    liveBlackjack: "cards",
    liveBaccarat: "gem",
    liveGameShows: "tent",
    livePoker: "spade",
    favRecent: "heart",
    favPlayed: "flame",
    favSlots: "tent",
    favLive: "dices",
    favDiscover: "sparkles",
    tourSoon: "calendar",
    tourMine: "target",
    tourDone: "check",
};

export const top10Games: CasinoGameRailCardData[] = [
    {
        id: "rail-top-aviator",
        title: "Aviator",
        provider: "Spribe",
        image: aviatorImage,
        badge: "#1",
        badgeTone: "gold",
    },
    {
        id: "rail-top-bonanza",
        title: "Sweet Bonanza",
        provider: "Pragmatic Play",
        image: bonanzaImage,
        badge: "#2",
        badgeTone: "silver",
    },
    {
        id: "rail-top-blackjack",
        title: "ONE Blackjack",
        provider: "Pragmatic Play",
        image: blackjackLiveImage,
        badge: "#3",
        badgeTone: "bronze",
    },
    {
        id: "rail-top-aviator-4",
        title: "Aviator",
        provider: "Spribe",
        image: aviatorImage,
        badge: "#4",
        badgeTone: "silver",
    },
    {
        id: "rail-top-bonanza-5",
        title: "Sweet Bonanza",
        provider: "Pragmatic Play",
        image: bonanzaImage,
        badge: "#5",
        badgeTone: "silver",
    },
];

export const lastPlayedGames: CasinoGameRailCardData[] = [
    {
        id: "rail-last-bonanza",
        title: "Sweet Bonanza",
        provider: "Pragmatic Play",
        image: bonanzaImage,
        badge: "Hace 5 min",
        badgeTone: "time",
    },
    {
        id: "rail-last-aviator",
        title: "Aviator",
        provider: "Spribe",
        image: aviatorImage,
        badge: "Hace 15 min",
        badgeTone: "time",
    },
    {
        id: "rail-last-blackjack",
        title: "ONE Blackjack",
        provider: "Pragmatic Play",
        image: blackjackLiveImage,
        badge: "Hace 1 hora",
        badgeTone: "time",
    },
    {
        id: "rail-last-bonanza-2",
        title: "Sweet Bonanza",
        provider: "Pragmatic Play",
        image: bonanzaImage,
        badge: "Hace 2 horas",
        badgeTone: "time",
    },
];

export const popularNowGames: CasinoGameRailCardData[] = [
    {
        id: "rail-popular-aviator",
        title: "Aviator",
        provider: "Spribe",
        image: aviatorImage,
        rtp: "97.00%",
        titleTone: "primary",
    },
    {
        id: "rail-popular-bonanza",
        title: "Sweet Bonanza",
        provider: "Pragmatic Play",
        image: bonanzaImage,
        rtp: "96.50%",
        titleTone: "danger",
    },
    {
        id: "rail-popular-blackjack",
        title: "ONE Blackjack",
        provider: "Pragmatic Play",
        image: blackjackLiveImage,
        rtp: "99.50%",
        titleTone: "secondary",
    },
    {
        id: "rail-popular-aviator-2",
        title: "Aviator",
        provider: "Spribe",
        image: aviatorImage,
        rtp: "97.00%",
        titleTone: "primary",
    },
];

export const topGames: CasinoGameRailCardData[] = [
    {
        id: "rail-games-aviator",
        title: "Aviator",
        provider: "Spribe",
        image: aviatorImage,
        badge: "HOT",
        badgeTone: "hot",
    },
    {
        id: "rail-games-moolah",
        title: "Mega Moolah",
        provider: "Microgaming",
        image: fireStrikeImage,
        badge: "JACKPOT",
        badgeTone: "jackpot",
        highlight: "377.892,38",
    },
    {
        id: "rail-games-roulette",
        title: "Lightning Roulette",
        provider: "Evolution",
        image: rouletteImage,
        badge: "VIVO",
        badgeTone: "vivo",
    },
    {
        id: "rail-games-bonanza",
        title: "Sweet Bonanza",
        provider: "Pragmatic Play",
        image: bonanzaImage,
        badge: "HOT",
        badgeTone: "hot",
    },
];

export const launchGames: CasinoGameRailCardData[] = [
    {
        id: "rail-launch-fire",
        title: "Fire Strike 2",
        provider: "Pragmatic Play",
        image: fireStrikeImage,
        badge: "NUEVO",
        badgeTone: "nuevo",
        titleTone: "danger",
    },
    {
        id: "rail-launch-mummy",
        title: "Mummy Hunter",
        provider: "Pragmatic Play",
        image: bookOfHeadImage,
        badge: "NUEVO",
        badgeTone: "nuevo",
        titleTone: "danger",
    },
    {
        id: "rail-launch-santa",
        title: "Santa's Village",
        provider: "Play'n GO",
        image: bonanzaImage,
        badge: "NUEVO",
        badgeTone: "nuevo",
        titleTone: "danger",
    },
    {
        id: "rail-launch-aviator",
        title: "Aviator",
        provider: "Spribe",
        image: aviatorImage,
        badge: "NUEVO",
        badgeTone: "nuevo",
        titleTone: "primary",
    },
];

export const jackpotGames: CasinoGameRailCardData[] = [
    {
        id: "rail-jackpot-slots",
        title: "Mega Slots",
        provider: "Microgaming",
        image: rouletteImage,
        badge: "JACKPOT",
        badgeTone: "jackpot",
        highlight: "$462K",
    },
    {
        id: "rail-jackpot-fire",
        title: "Fire Strike",
        provider: "Pragmatic Play",
        image: fireStrikeImage,
        badge: "JACKPOT",
        badgeTone: "jackpot",
        highlight: "$740K",
    },
    {
        id: "rail-jackpot-moolah",
        title: "Mega Moolah",
        provider: "Microgaming",
        image: bookOfHeadImage,
        badge: "JACKPOT",
        badgeTone: "jackpot",
        highlight: "$669K",
    },
    {
        id: "rail-jackpot-bonanza",
        title: "Sweet Bonanza",
        provider: "Pragmatic Play",
        image: bonanzaImage,
        badge: "JACKPOT",
        badgeTone: "jackpot",
        highlight: "$318K",
    },
];

export const megawaysGames: CasinoGameRailCardData[] = [
    {
        id: "rail-mega-neon",
        title: "MEGAWAYS",
        provider: "Big Time Gaming",
        image: rouletteImage,
        titleTone: "danger",
    },
    {
        id: "rail-mega-reels",
        title: "MEGAWAYS",
        provider: "Pragmatic Play",
        image: bonanzaImage,
        titleTone: "danger",
    },
    {
        id: "rail-mega-jackpot",
        title: "MEGAWAYS",
        provider: "Microgaming",
        image: fireStrikeImage,
        titleTone: "danger",
    },
    {
        id: "rail-mega-aviator",
        title: "MEGAWAYS",
        provider: "Spribe",
        image: aviatorImage,
        titleTone: "danger",
    },
];

export const forYouGames: CasinoGameRailCardData[] = [
    {
        id: "rail-foryou-aviator",
        title: "Aviator",
        provider: "Spribe",
        image: aviatorImage,
        badge: "PARA TI",
        badgeTone: "brand",
        rtp: "97.00%",
        titleTone: "primary",
    },
    {
        id: "rail-foryou-bonanza",
        title: "Sweet Bonanza",
        provider: "Pragmatic Play",
        image: bonanzaImage,
        badge: "PARA TI",
        badgeTone: "brand",
        rtp: "96.51%",
        titleTone: "danger",
    },
    {
        id: "rail-foryou-blackjack",
        title: "ONE Blackjack",
        provider: "Pragmatic Play",
        image: blackjackLiveImage,
        badge: "PARA TI",
        badgeTone: "brand",
        rtp: "99.50%",
        titleTone: "secondary",
    },
    {
        id: "rail-foryou-fire",
        title: "Fire Strike 2",
        provider: "Pragmatic Play",
        image: fireStrikeImage,
        badge: "PARA TI",
        badgeTone: "brand",
        rtp: "96.12%",
        titleTone: "danger",
    },
];

export const basedOnGames: CasinoGameRailCardData[] = [
    {
        id: "rail-based-fire",
        title: "Fire Strike 2",
        provider: "Pragmatic Play",
        image: fireStrikeImage,
        rtp: "96.12%",
        titleTone: "danger",
    },
    {
        id: "rail-based-mummy",
        title: "Mummy Hunter",
        provider: "Pragmatic Play",
        image: bookOfHeadImage,
        rtp: "96.48%",
        titleTone: "danger",
    },
    {
        id: "rail-based-santa",
        title: "Santa's Village",
        provider: "Play'n GO",
        image: bonanzaImage,
        rtp: "96.70%",
        titleTone: "danger",
    },
    {
        id: "rail-based-aviator",
        title: "Aviator",
        provider: "Spribe",
        image: aviatorImage,
        rtp: "97.00%",
        titleTone: "primary",
    },
];

export const similarGames: CasinoGameRailCardData[] = [
    {
        id: "rail-similar-santa",
        title: "Santa's Village",
        provider: "Play'n GO",
        image: bonanzaImage,
        rtp: "96.70%",
        titleTone: "danger",
    },
    {
        id: "rail-similar-volcanoes",
        title: "5 Spirit Volcanoes",
        provider: "Pragmatic Play",
        image: rouletteImage,
        rtp: "96.52%",
        titleTone: "danger",
    },
    {
        id: "rail-similar-bomb",
        title: "Bomb Runner",
        provider: "Microgaming",
        image: fireStrikeImage,
        rtp: "96.45%",
        titleTone: "danger",
    },
    {
        id: "rail-similar-blackjack",
        title: "ONE Blackjack",
        provider: "Pragmatic Play",
        image: blackjackLiveImage,
        rtp: "99.50%",
        titleTone: "secondary",
    },
];

export const trendingGames: CasinoGameRailCardData[] = [
    {
        id: "rail-trending-blackjack",
        title: "ONE Blackjack",
        provider: "Pragmatic Play",
        image: blackjackLiveImage,
        badge: "TRENDING",
        badgeTone: "brand",
        rtp: "99.50%",
        titleTone: "secondary",
    },
    {
        id: "rail-trending-fire",
        title: "Fire Strike 2",
        provider: "Pragmatic Play",
        image: fireStrikeImage,
        badge: "TRENDING",
        badgeTone: "brand",
        rtp: "96.12%",
        titleTone: "danger",
    },
    {
        id: "rail-trending-mummy",
        title: "Mummy Hunter",
        provider: "Pragmatic Play",
        image: bookOfHeadImage,
        badge: "TRENDING",
        badgeTone: "brand",
        rtp: "96.48%",
        titleTone: "danger",
    },
    {
        id: "rail-trending-aviator",
        title: "Aviator",
        provider: "Spribe",
        image: aviatorImage,
        badge: "TRENDING",
        badgeTone: "brand",
        rtp: "97.00%",
        titleTone: "primary",
    },
];

export const upcomingGames: CasinoGameRailCardData[] = [
    {
        id: "rail-upcoming-head",
        title: "Book of Head",
        provider: "Play'n GO",
        image: bookOfHeadImage,
        badge: "PRONTO",
        badgeTone: "brand",
        highlight: "$274K",
    },
    {
        id: "rail-upcoming-santa",
        title: "Santa's Village",
        provider: "Play'n GO",
        image: bonanzaImage,
        badge: "PRONTO",
        badgeTone: "brand",
        highlight: "$265K",
    },
    {
        id: "rail-upcoming-slots",
        title: "Mega Slots",
        provider: "Microgaming",
        image: rouletteImage,
        badge: "PRONTO",
        badgeTone: "brand",
        highlight: "$351K",
    },
    {
        id: "rail-upcoming-fire",
        title: "Fire Strike",
        provider: "Pragmatic Play",
        image: fireStrikeImage,
        badge: "PRONTO",
        badgeTone: "brand",
        highlight: "$198K",
    },
];

export const liveTopGames: CasinoGameRailCardData[] = [
    {
        id: "rail-live-top-aviator",
        title: "Aviator",
        provider: "Spribe",
        image: aviatorImage,
        badge: "#1",
        badgeTone: "gold",
        titleTone: "primary",
    },
    {
        id: "rail-live-top-bonanza",
        title: "Sweet Bonanza",
        provider: "Pragmatic Play",
        image: bonanzaImage,
        badge: "#2",
        badgeTone: "silver",
        titleTone: "danger",
    },
    {
        id: "rail-live-top-blackjack",
        title: "ONE Blackjack",
        provider: "Pragmatic Play",
        image: blackjackLiveImage,
        badge: "#3",
        badgeTone: "bronze",
        titleTone: "secondary",
    },
    {
        id: "rail-live-top-roulette",
        title: "Lightning Roulette",
        provider: "Evolution",
        image: rouletteImage,
        badge: "#4",
        badgeTone: "silver",
        titleTone: "danger",
    },
];

export const liveRouletteGames: CasinoGameRailCardData[] = [
    {
        id: "rail-live-roulette-aviator",
        title: "Aviator",
        provider: "Spribe",
        image: aviatorImage,
        badge: "VIVO",
        badgeTone: "hot",
        titleTone: "primary",
    },
    {
        id: "rail-live-roulette-bonanza",
        title: "Sweet Bonanza",
        provider: "Pragmatic Play",
        image: bonanzaImage,
        badge: "VIVO",
        badgeTone: "hot",
        titleTone: "danger",
    },
    {
        id: "rail-live-roulette-blackjack",
        title: "ONE Blackjack",
        provider: "Pragmatic Play",
        image: blackjackLiveImage,
        badge: "VIVO",
        badgeTone: "hot",
        titleTone: "secondary",
    },
    {
        id: "rail-live-roulette-lightning",
        title: "Lightning Roulette",
        provider: "Evolution",
        image: rouletteImage,
        badge: "VIVO",
        badgeTone: "hot",
        titleTone: "danger",
    },
];

export const liveBlackjackGames: CasinoGameRailCardData[] = [
    {
        id: "rail-live-blackjack-one",
        title: "ONE Blackjack",
        provider: "Pragmatic Play",
        image: blackjackLiveImage,
        badge: "VIVO",
        badgeTone: "hot",
        titleTone: "secondary",
    },
    {
        id: "rail-live-blackjack-fire",
        title: "Fire Strike 2",
        provider: "Pragmatic Play",
        image: fireStrikeImage,
        badge: "VIVO",
        badgeTone: "hot",
        titleTone: "danger",
    },
    {
        id: "rail-live-blackjack-mummy",
        title: "Mummy Hunter",
        provider: "Pragmatic Play",
        image: bookOfHeadImage,
        badge: "VIVO",
        badgeTone: "hot",
        titleTone: "danger",
    },
    {
        id: "rail-live-blackjack-aviator",
        title: "Aviator",
        provider: "Spribe",
        image: aviatorImage,
        badge: "VIVO",
        badgeTone: "hot",
        titleTone: "primary",
    },
];

export const liveBaccaratGames: CasinoGameRailCardData[] = [
    {
        id: "rail-live-baccarat-mummy",
        title: "Mummy Hunter",
        provider: "Pragmatic Play",
        image: bookOfHeadImage,
        badge: "VIVO",
        badgeTone: "hot",
        titleTone: "danger",
    },
    {
        id: "rail-live-baccarat-santa",
        title: "Santa's Village",
        provider: "Play'n GO",
        image: bonanzaImage,
        badge: "VIVO",
        badgeTone: "hot",
        titleTone: "danger",
    },
    {
        id: "rail-live-baccarat-volcanoes",
        title: "5 Spirit Volcanoes",
        provider: "Pragmatic Play",
        image: rouletteImage,
        badge: "VIVO",
        badgeTone: "hot",
        titleTone: "danger",
    },
    {
        id: "rail-live-baccarat-blackjack",
        title: "ONE Blackjack",
        provider: "Pragmatic Play",
        image: blackjackLiveImage,
        badge: "VIVO",
        badgeTone: "hot",
        titleTone: "secondary",
    },
];

export const liveGameShowGames: CasinoGameRailCardData[] = [
    {
        id: "rail-live-show-bonanza",
        title: "Sweet Bonanza",
        provider: "Pragmatic Play",
        image: bonanzaImage,
        badge: "SHOW",
        badgeTone: "show",
        titleTone: "danger",
    },
    {
        id: "rail-live-show-blackjack",
        title: "ONE Blackjack",
        provider: "Pragmatic Play",
        image: blackjackLiveImage,
        badge: "SHOW",
        badgeTone: "show",
        titleTone: "secondary",
    },
    {
        id: "rail-live-show-fire",
        title: "Fire Strike 2",
        provider: "Pragmatic Play",
        image: fireStrikeImage,
        badge: "SHOW",
        badgeTone: "show",
        titleTone: "danger",
    },
    {
        id: "rail-live-show-aviator",
        title: "Aviator",
        provider: "Spribe",
        image: aviatorImage,
        badge: "SHOW",
        badgeTone: "show",
        titleTone: "primary",
    },
];

export const livePokerGames: CasinoGameRailCardData[] = [
    {
        id: "rail-live-poker-fire",
        title: "Fire Strike 2",
        provider: "Pragmatic Play",
        image: fireStrikeImage,
        badge: "VIVO",
        badgeTone: "hot",
        titleTone: "danger",
    },
    {
        id: "rail-live-poker-mummy",
        title: "Mummy Hunter",
        provider: "Pragmatic Play",
        image: bookOfHeadImage,
        badge: "VIVO",
        badgeTone: "hot",
        titleTone: "danger",
    },
    {
        id: "rail-live-poker-santa",
        title: "Santa's Village",
        provider: "Play'n GO",
        image: bonanzaImage,
        badge: "VIVO",
        badgeTone: "hot",
        titleTone: "danger",
    },
    {
        id: "rail-live-poker-blackjack",
        title: "ONE Blackjack",
        provider: "Pragmatic Play",
        image: blackjackLiveImage,
        badge: "VIVO",
        badgeTone: "hot",
        titleTone: "secondary",
    },
];

export const favRecentGames: CasinoGameRailCardData[] = [
    {
        id: "rail-fav-recent-aviator",
        title: "Aviator",
        provider: "Spribe",
        image: aviatorImage,
        caption: "Hace 2 días",
        titleTone: "primary",
    },
    {
        id: "rail-fav-recent-bonanza",
        title: "Sweet Bonanza",
        provider: "Pragmatic Play",
        image: bonanzaImage,
        caption: "Hace 2 días",
        titleTone: "danger",
    },
    {
        id: "rail-fav-recent-blackjack",
        title: "ONE Blackjack",
        provider: "Pragmatic Play",
        image: blackjackLiveImage,
        caption: "Hace 2 días",
        titleTone: "secondary",
    },
    {
        id: "rail-fav-recent-fire",
        title: "Fire Strike 2",
        provider: "Pragmatic Play",
        image: fireStrikeImage,
        caption: "Hace 2 días",
        titleTone: "danger",
    },
];

export const favPlayedGames: CasinoGameRailCardData[] = [
    {
        id: "rail-fav-played-blackjack",
        title: "ONE Blackjack",
        provider: "Pragmatic Play",
        image: blackjackLiveImage,
        caption: "33 veces",
        titleTone: "secondary",
    },
    {
        id: "rail-fav-played-fire",
        title: "Fire Strike 2",
        provider: "Pragmatic Play",
        image: fireStrikeImage,
        caption: "12 veces",
        titleTone: "danger",
    },
    {
        id: "rail-fav-played-mummy",
        title: "Mummy Hunter",
        provider: "Pragmatic Play",
        image: bookOfHeadImage,
        caption: "42 veces",
        titleTone: "danger",
    },
    {
        id: "rail-fav-played-aviator",
        title: "Aviator",
        provider: "Spribe",
        image: aviatorImage,
        caption: "18 veces",
        titleTone: "primary",
    },
];

export const favSlotsGames: CasinoGameRailCardData[] = [
    {
        id: "rail-fav-slots-bonanza",
        title: "Sweet Bonanza",
        provider: "Pragmatic Play",
        image: bonanzaImage,
        rtp: "96.51%",
        titleTone: "danger",
    },
    {
        id: "rail-fav-slots-blackjack",
        title: "ONE Blackjack",
        provider: "Pragmatic Play",
        image: blackjackLiveImage,
        rtp: "99.50%",
        titleTone: "secondary",
    },
    {
        id: "rail-fav-slots-fire",
        title: "Fire Strike 2",
        provider: "Pragmatic Play",
        image: fireStrikeImage,
        rtp: "96.12%",
        titleTone: "danger",
    },
    {
        id: "rail-fav-slots-aviator",
        title: "Aviator",
        provider: "Spribe",
        image: aviatorImage,
        rtp: "97.00%",
        titleTone: "primary",
    },
];

export const favLiveGames: CasinoGameRailCardData[] = [
    {
        id: "rail-fav-live-mummy",
        title: "Mummy Hunter",
        provider: "Pragmatic Play",
        image: bookOfHeadImage,
        badge: "VIVO",
        badgeTone: "hot",
    },
    {
        id: "rail-fav-live-santa",
        title: "Santa's Village",
        provider: "Habanero",
        image: bonanzaImage,
        badge: "VIVO",
        badgeTone: "hot",
    },
    {
        id: "rail-fav-live-slots",
        title: "Lightning Roulette",
        provider: "Pragmatic Play",
        image: rouletteImage,
        badge: "VIVO",
        badgeTone: "hot",
    },
    {
        id: "rail-fav-live-blackjack",
        title: "ONE Blackjack",
        provider: "Pragmatic Play",
        image: blackjackLiveImage,
        badge: "VIVO",
        badgeTone: "hot",
    },
];

export const favDiscoverGames: CasinoGameRailCardData[] = [
    {
        id: "rail-fav-discover-fire",
        title: "Fire Strike 2",
        provider: "Pragmatic Play",
        image: fireStrikeImage,
        caption: "Hace 15 días",
        titleTone: "danger",
    },
    {
        id: "rail-fav-discover-mummy",
        title: "Mummy Hunter",
        provider: "Pragmatic Play",
        image: bookOfHeadImage,
        caption: "Hace 15 días",
        titleTone: "danger",
    },
    {
        id: "rail-fav-discover-santa",
        title: "Santa's Village",
        provider: "Play'n GO",
        image: bonanzaImage,
        caption: "Hace 15 días",
        titleTone: "danger",
    },
    {
        id: "rail-fav-discover-aviator",
        title: "Aviator",
        provider: "Spribe",
        image: aviatorImage,
        caption: "Hace 15 días",
        titleTone: "primary",
    },
];

export const tourSoonGames: CasinoGameRailCardData[] = [
    {
        id: "rail-tour-soon-aviator",
        title: "Aviator",
        provider: "Spribe",
        image: aviatorImage,
        badge: "PRONTO",
        badgeTone: "pronto",
        caption: "Comienza en 2h",
        captionTone: "primary",
    },
    {
        id: "rail-tour-soon-bonanza",
        title: "Sweet Bonanza",
        provider: "Pragmatic Play",
        image: bonanzaImage,
        badge: "PRONTO",
        badgeTone: "pronto",
        caption: "Comienza en 2h",
        captionTone: "primary",
    },
    {
        id: "rail-tour-soon-blackjack",
        title: "ONE Blackjack",
        provider: "Pragmatic Play",
        image: blackjackLiveImage,
        badge: "PRONTO",
        badgeTone: "pronto",
        caption: "Comienza en 2h",
        captionTone: "primary",
    },
    {
        id: "rail-tour-soon-fire",
        title: "Fire Strike 2",
        provider: "Pragmatic Play",
        image: fireStrikeImage,
        badge: "PRONTO",
        badgeTone: "pronto",
        caption: "Comienza en 2h",
        captionTone: "primary",
    },
];

export const tourMineGames: CasinoGameRailCardData[] = [
    {
        id: "rail-tour-mine-blackjack",
        title: "ONE Blackjack",
        provider: "Pragmatic Play",
        image: blackjackLiveImage,
        badge: "PARTICIPANDO",
        badgeTone: "playing",
        caption: "Posición #45",
        captionTone: "success",
    },
    {
        id: "rail-tour-mine-fire",
        title: "Fire Strike 2",
        provider: "Pragmatic Play",
        image: fireStrikeImage,
        badge: "PARTICIPANDO",
        badgeTone: "playing",
        caption: "Posición #45",
        captionTone: "success",
    },
    {
        id: "rail-tour-mine-mummy",
        title: "Mummy Hunter",
        provider: "Pragmatic Play",
        image: bookOfHeadImage,
        badge: "PARTICIPANDO",
        badgeTone: "playing",
        caption: "Posición #45",
        captionTone: "success",
    },
    {
        id: "rail-tour-mine-aviator",
        title: "Aviator",
        provider: "Spribe",
        image: aviatorImage,
        badge: "PARTICIPANDO",
        badgeTone: "playing",
        caption: "Posición #45",
        captionTone: "success",
    },
];

export const tourDoneGames: CasinoGameRailCardData[] = [
    {
        id: "rail-tour-done-mummy",
        title: "Mummy Hunter",
        provider: "Pragmatic Play",
        image: bookOfHeadImage,
        badge: "FINALIZADO",
        badgeTone: "done",
        caption: "Premio: $250",
        captionTone: "primary",
    },
    {
        id: "rail-tour-done-santa",
        title: "Santa's Village",
        provider: "Play'n GO",
        image: bonanzaImage,
        badge: "FINALIZADO",
        badgeTone: "done",
        caption: "Premio: $250",
        captionTone: "primary",
    },
    {
        id: "rail-tour-done-slots",
        title: "Lightning Roulette",
        provider: "Pragmatic Play",
        image: rouletteImage,
        badge: "FINALIZADO",
        badgeTone: "done",
        caption: "Premio: $250",
        captionTone: "primary",
    },
    {
        id: "rail-tour-done-blackjack",
        title: "ONE Blackjack",
        provider: "Pragmatic Play",
        image: blackjackLiveImage,
        badge: "FINALIZADO",
        badgeTone: "done",
        caption: "Premio: $250",
        captionTone: "primary",
    },
];

export const casinoGameRailItems: Record<CasinoGameRailVariant, CasinoGameRailCardData[]> = {
    rank: top10Games,
    time: lastPlayedGames,
    popular: popularNowGames,
    topGames,
    launches: launchGames,
    jackpots: jackpotGames,
    megaways: megawaysGames,
    forYou: forYouGames,
    basedOn: basedOnGames,
    similar: similarGames,
    trending: trendingGames,
    upcoming: upcomingGames,
    liveTop: liveTopGames,
    liveRoulette: liveRouletteGames,
    liveBlackjack: liveBlackjackGames,
    liveBaccarat: liveBaccaratGames,
    liveGameShows: liveGameShowGames,
    livePoker: livePokerGames,
    favRecent: favRecentGames,
    favPlayed: favPlayedGames,
    favSlots: favSlotsGames,
    favLive: favLiveGames,
    favDiscover: favDiscoverGames,
    tourSoon: tourSoonGames,
    tourMine: tourMineGames,
    tourDone: tourDoneGames,
};
